<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    	<!-- <a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="btn btn-primary btn-xs pull-right">
    		Add New Customer
    	</a> -->
	  	<tr>
		    <th>Id</th>
		    <th>Name</th>
		    <th>Email</th>
		    <th>Password</th>
<!-- 		    <th>Group</th> -->
<!-- 		    <th>Customer Since</th> -->
<!-- 		    <th>Date of Birth</th> -->
		    <th></th>
		    <th></th>
		    <th></th>
	    </tr>
    </thead>
    <?php
    
    $customers = $block->getCustomers();
    
    foreach ($customers as $customer) {
    	echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
    	echo "<td>".$customer->getId()."</td>";
    	echo "<td>".$customer->getName()."</td>";
    	echo "<td>".$customer->getEmail()."</td>";
    	echo "<td>".$customer->getPasswordHash()."</td>";
//     	echo "<td>".$block->getGroupName($customer->getGroupId())."</td>";
//     	echo "<td>".."</td>";
//     	echo "<td>".."</td>";
    	echo "<td><a title='Change customer\'s password' href=" . $block->getBaseUrl() . "customermanager/index/changepassword?customer_id=" . $customer->getId() . ">Change Password</a></td>";
    	echo "<td><a title='Edit customer' href=" . $block->getBaseUrl() . "customermanager/index/edit?customer_id=" . $customer->getId() . ">Edit</a></td>";
    	echo "<td><a title='Delete customer' href=" . $block->getBaseUrl() . "customermanager/index/edit?delete_id=" . $customer->getId() . ">Delete</a></td>";
    	echo "</tr>";
    }
    ?>
</table>
