<?php 
// Check if customer has logged in
if ($block->isCustomerLoggedIn()):
    $currentCustomerId = $block->getCustomerId();
?>
    <div class="block block-poll">
    	
        <?php 
        $activePolls = $block->getActivePolls();
        
        // If there are any active polls
        // render block title
        if ($activePolls->count() > 0):
        ?>
        
            <!-- Block title -->
            <div class="block-title">
        		<strong role="heading" aria-level="2">Polls</strong>
        	</div>
        
        <?php 
        // END rendering block title
        endif;
        // BEGIN rendering poll form(s)
        foreach ($activePolls as $poll):
            $pollId = $poll->getPoll_id();
        ?>
    
            <div class="container poll-wrapper">
            	<p class="poll-content" >
            		<?= $poll->getPoll_content(); ?>
            	</p>
            	<form method='POST' action="/polls/poll/submit" id="poll-form-<?= $pollId ?>">
            		<input type="hidden" name="current-page" value="<?= $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" >
            		<input type="hidden" name="poll_id" value="<?= $pollId ?>">
            		<input type="hidden" name="customer_id" value="<?= $currentCustomerId ?>">
            		
            		<?php 
            		// retrieve list of answers respective to current poll
            		$answers = $block->getAnswersByPollId($pollId);
            		
            		// Check if poll is already answered by current customer
            		if (! $block->isPollAnsweredByCustomer($pollId, $currentCustomerId)):
                		// NO
                		// Render Answers options
                    ?>
                		<?php  
                		// BEGIN rendering answer options
                		foreach ($answers as $ans):
                            $ansId = $ans->getAnswer_id();
                		?>
                		
                    		<div class="form-check">
                      			<input class="form-check-input" type="radio" name="answer_id" id="option-<?= $ansId; ?>" value="<?= $ansId; ?>">
                      			<label class="form-check-label" for="option-<?= $ansId; ?>">
                        			<?= $ans->getAnswer_content(); ?>
                      			</label>
                    		</div>
                		
            			<?php 
                		// END rendering answer options
                		endforeach;
                	    ?>
                	
                	<br>
            		<!-- Poll Submit Button -->
            	    <button type="submit" class="btn btn-primary" name="submit-poll">Submit</button>
                	
                	<?php
                	else:
                        // YES
                        // Render Answer contents with results
                	   
                        // retrieve the answer submitted by this current customer
                        $customerSubmission = $block->getSubmissionByPollIdAndCustomerId($pollId, $currentCustomerId);
                        
                        foreach ($answers as $ans):
                    	   $ansId = $ans->getAnswer_id();
            		?>    
            		
            				<div class="form-check">
                      			<label class="form-check-label" for="option-<?= $ansId; ?>">
                        			<?php 
                                        if ($customerSubmission->getAnswer_id() == $ansId):
                                            // BEGIN render answer with emphasis style
                        			?>
                        					<em class="customer-answer">
                        						<?= $ans->getAnswer_content(); ?>&nbsp;
                        						(Your answer):
                        					</em>
                        			<?php 
                                            // END render answer with emphasis style
                                            
                                        else:
                                            // BEGIN render answer with normal style
                        			?>
                        					<?= $ans->getAnswer_content(); ?> :
                        			<?php
                                            // END render answer with normal style
                                        endif;
                        			?>
                        			<strong>
                        				<?php
                        				    // total number of submissions to this poll
                        				    $totalSubmission = $block->countCollectionItems(
                        				        $block->getSubmissionsByPollId($pollId)
                        				    );
                        				    // total number of this particular answer
                        				    $totalCurrentAnswer = $block->countCollectionItems(
                        				        $block->getSubmissionsByPollIdAndAnswerId($pollId, $ansId)
                        				    );
                        				    // calculate and display result
                        				    echo round(($totalCurrentAnswer / $totalSubmission * 100), 2) . "%";
                        				?>
                        			</strong>
                      			</label>
                    		</div>
            				
            			<?php 
            		    // END rendering answer contents with results
            		    endforeach;
            		    ?>
            		    
            		    <!-- Thank-you message -->
            		    <div class="poll-thankyou">Thank you for letting us know your opinion!</div>
            		    
            		<?php
            		// END Check if poll is already answered by current customer
            		endif;
            		?>
            	</form>
            </div>
        
        <?php 
        // END rendering poll form(s)
        endforeach;
        ?>
    </div>

<?php 
// END check login
endif;
?>

<!-- Internal styling - must remove and replace with proper methodology later on -->
<style>
.poll-wrapper {
    margin: 20px 0;
    padding: 35px;
    border: 1px solid #ccc;
}

.poll-content {
    font-weight: bold;
    font-style: italic;
}

.block-poll .block-title strong {
    font-size: 18px;
    font-weight: 300;
}

.customer-answer {
    font-weight: bold;
}

.poll-thankyou {
    margin-top: 15px;
    font-style: italic;
    letter-spacing: 0.5px;
}
</style>