<div class="container">
	<p>This is a poll question.</p>
	<form method='POST' action="/polls/poll/save" id="poll-form">
		<div class="form-check">
  			<input class="form-check-input" type="radio" name="answer" id="option1" value="option1" checked>
  			<label class="form-check-label" for="option1">
    			Option 1
  			</label>
		</div>
		<div class="form-check">
  			<input class="form-check-input" type="radio" name="answer" id="option2" value="option2">
  			<label class="form-check-label" for="option2">
    			Option 2
  			</label>
		</div>
		<div class="form-check">
  			<input class="form-check-input" type="radio" name="answer" id="option3" value="option3">
  			<label class="form-check-label" for="option3">
    			Option 3
  			</label>
		</div>
		<br>
	    <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
	</form>
</div>